abs/urls.py
from django.urls import path

from abs.views import IndexViews,AddCustomerView,CustomerDetailView,AccountCardsListView,EditCustomerView,CustomerDeleteView,AddAccountView,CreateContractView,ClientAccountsReportView

urlpatterns = [
    path('', IndexViews.as_view(), name = "customer_list"),
    path('add_customer/', AddCustomerView.as_view(),name='add_customer'),
    path('customer_detail/<int:pk>', CustomerDetailView.as_view(),name='customer_detail'),
    path('acount_cards/<int:pk>', AccountCardsListView.as_view(),name='account_cards'),
    path('edit_customer/<int:pk>', EditCustomerView.as_view(),name='edit_customer'),
    path('delete_customer/<int:pk>', CustomerDeleteView.as_view(),name='delete_customer'),
    path('add_account/<int:pk>', AddAccountView.as_view(),name='add_account'),
    path('create_contract', CreateContractView.as_view(),name='create_contract'),
    path('spravka', ClientAccountsReportView.as_view(),name='spravka'),
]

bis/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("abs.urls"))

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

abs/models.py
from django.db import models

class Customers (models.Model):
    last_name = models.CharField(max_length = 150, verbose_name = "Фамилия")
    first_name = models.CharField(max_length = 150,verbose_name = "Имя")
    middle_name = models.CharField(max_length = 150, verbose_name = "Отчество", blank = True)
    gender = models.CharField(max_length=1, choices=[("М", "Мужской"),("Ж", "Женский")])
    address = models.TextField(verbose_name = "Адрес проживание")
    email = models.EmailField(verbose_name = "Адрес электронной почты")
    phone_numder = models.CharField(max_length = 15,verbose_name = "Телефон")
    password_number = models.CharField(max_length = 10, verbose_name = "Номер паспорта")
    password_issue_data = models.DateField(verbose_name = "Дата получения паспорта",unique = True)
    date_of_birth = models.DateField(verbose_name = "День рождения" ,default="2000-01-01")
    # created_at = models.DateTimeField(auto_now_add = True, verbose_name = "Дата открытие счёта")
    photo = models.ImageField(verbose_name="Фото", default="None",upload_to="upload/product")

    def __str__(self):
        return f"{self.pk} {self.last_name} {self.first_name} {self.middle_name}"

    def get_customer_by_paspord(password_number):
        try:
            return Customers.objects.get(password_number= password_number)
        except:
            return False
    def get_customer_by_id(id):
        try:
            return Customers.objects.get(pk= id)
        except:
            return False

class Currencys (models.Model):
    name = models.CharField(max_length = 150, verbose_name = "Валюта", unique = True)
    code = models.CharField(max_length = 3, unique = True)
    symbol = models.CharField(max_length = 5, blank = True, null = True, default=' ')

    def __str__(self) :
        return f"{self.name}"

class Account (models.Model):

    customer = models.ForeignKey(Customers, on_delete = models.CASCADE,related_name = "customer")
    account_type = models.CharField(max_length = 1, choices = [("Д", "Дебетовый"), ("К","Кредитный"), ("Н","Накопительный")], default="Д")
    currency = models.ForeignKey(Currencys, verbose_name = "Валюта",on_delete=models.CASCADE, default='')
    status = models.CharField(max_length = 20,choices =[("a",'active'),('d','disactive')], default = "active", verbose_name = "Статус счёта")
    opened_at = models.DateField(auto_now_add = True ,verbose_name = "Дата открытие счёта")
    closed_at = models.DateField(blank = True, null = True)

    def __str__(self):
        return f"{self.pk} {self.customer}"

class Card(models.Model):
    card_number = models.CharField(max_length = 16, unique = True, verbose_name = "Номер карты")
    expiration_date = models.DateField(verbose_name = "Срок окончание действие карты")
    customer = models.ForeignKey(Customers, on_delete = models.CASCADE)
    account = models.ForeignKey(Account, on_delete = models.CASCADE)



# Create your models here.

abs/forms.py
# from django import forms
# from .models import Customers

# class CustomerForm(forms.ModelForm):
#     class Meta:
#         model = Customers
#         fields = ['first_name', 'last_name', 'email', 'phone']  # Поля, которые будут отображаться в форме

#     # def __init__(self, *args, **kwargs):
#     #     super(CustomerForm, self).__init__(*args, **kwargs)
#     #     self.fields['first_name'].widget.attrs.update({'class': 'form-control', 'placeholder': 'First Name'})
#     #     self.fields['last_name'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Last Name'})
#     #     self.fields['email'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Email'})
#     #     self.fields['phone'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Phone'})

abs/views.py
from django.shortcuts import render,get_object_or_404
from django.views.generic import ListView,View,DetailView,UpdateView,DeleteView
from .models import Customers,Account,Card,Currencys
from django.shortcuts import redirect
from django.http.response import HttpResponseRedirect
from django.urls import reverse_lazy
from datetime import datetime
from django.http import FileResponse
from django.views.generic import View
from docx import Document
from datetime import datetime
import io


class IndexViews(ListView):
    template_name = "index.html"
    model = Customers



class AddCustomerView(ListView):
    template_name = "add_customers.html"
    model = Customers

    def post(self, request, **kwargs):
        last_name = request.POST.get('last_name')
        first_name = request.POST.get('first_name')
        middle_name = request.POST.get('middle_name')
        date_of_birth = request.POST.get('date_of_birth')
        gender = request.POST.get('gender')
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        address = request.POST.get('address')
        passport_number = request.POST.get('passport_number')
        password_issue_data = request.POST.get('password_issue_data')
        photo = request.FILES.get('photo')

        check_passport_number=Customers.get_customer_by_paspord(passport_number)

        if not check_passport_number:
            customer=Customers(last_name = last_name,
                               first_name = first_name,
                               middle_name = middle_name,
                               gender = gender,
                               address = address,
                               email=email,
                               phone_numder = phone,
                               password_number = passport_number,
                               password_issue_data = password_issue_data,
                               date_of_birth=date_of_birth,
                               photo=photo
                               )
            customer.save()
            # request.session["customer"]=email


            response=HttpResponseRedirect(redirect_to="/")
            return response
        else:
            response=HttpResponseRedirect(redirect_to=".")
            return response


class CustomerDetailView(DetailView):
    model = Customers
    template_name = 'customers_detail.html'
    context_object_name = 'customer'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        customer = self.get_object()
        context['accounts'] =Account.objects.filter(customer=customer)
        return context

    def post(self, request, **kwargs):
        account_pk = request.POST.get('account_pk')
        account = get_object_or_404(Account, id=account_pk)
        account.status = "disactive"
        account.closed_at   = datetime.now()

        account.save()
        return self.get(request)



class AccountCardsListView(ListView):
    model = Card
    template_name = 'account_cards.html'
    context_object_name = 'cards'

    def get_queryset(self):
        account_id = self.kwargs['pk']
        account = get_object_or_404(Account, pk=account_id)
        return Card.objects.filter(account=account)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        account_id = self.kwargs['pk']
        context['account'] = get_object_or_404(Account, pk=account_id)
        return context
    def post(self, request, **kwargs):
        account_pk = request.POST.get('account_pk')
        customer_pk = request.POST.get('customer_pk')
        prefix = '2200'  # Префикс для карт "Мир"
        length = 16  # Длина номера карты
        valid_card_number = generate_valid_card_number(prefix, length)
        current_time=datetime.now()
        current_time=add_years(current_time,10)





        card=Card(
            card_number=valid_card_number,
            expiration_date=current_time,
            customer=Customers.objects.get(pk=customer_pk),
            account=Account.objects.get(pk=account_pk)
        )
        card.save()
        # response=HttpResponseRedirect(redirect_to = '')
        return self.get(request)



class EditCustomerView(UpdateView):
    model = Customers
    fields = []  # Список полей, которые будут доступны для редактирования
    template_name = 'edit_customer.html'
    success_url = '/customer_list/'  # URL для перенаправления после успешного редактирования

    def get_object(self, queryset=None):
        # Получаем клиента по его идентификатору
        return get_object_or_404(Customers, id=self.kwargs['pk'])

    def post(self, request, **kwargs):
        customer = get_object_or_404(Customers, id=self.kwargs['pk'])
        last_name = request.POST.get('last_name')
        first_name = request.POST.get('first_name')
        middle_name = request.POST.get('middle_name')
        date_of_birth = request.POST.get('date_of_birth')
        gender = request.POST.get('gender')
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        address = request.POST.get('address')
        password_number = request.POST.get('passport_number')
        password_issue_data = request.POST.get('password_issue_data')

        # check_passport_number=Customers.get_customer_by_paspord(password_number)

        customer.last_name = last_name
        customer.first_name = first_name
        customer.middle_name = middle_name
        customer.gender = gender
        customer.address = address
        customer.email = email
        customer.phone_numder = phone
        customer.password_number = password_number
        customer.password_issue_data = password_issue_data
        customer.date_of_birth = date_of_birth



        customer.save()
        # request.session["customer"]=email


        return redirect(reverse_lazy('customer_detail', kwargs={'pk': self.kwargs['pk']}))
class CustomerDeleteView(DeleteView):
    model = Customers
    template_name = 'confirm_delete_customer.html'
    success_url = reverse_lazy('customer_list')

class AddAccountView(ListView):
    model = Account
    template_name = "add_account.html"
    def get(self, request,pk):

        currencies = Currencys.objects.all()
        return render(request, self.template_name, {'currencies': currencies ,"customer":pk})

    def post(self, request, **kwargs):
        customer_pk = request.POST.get("customer_pk")
        type_account =request.POST.get("type_account")
        currency_id =request.POST.get("currency")



        account =Account(customer=Customers.objects.get(pk=customer_pk),
                         account_type=type_account,
                         currency=Currencys.objects.get(pk=currency_id),
                         opened_at=datetime.now())
        account.save()
        return redirect(reverse_lazy('customer_detail', kwargs={'pk': customer_pk}))

class CreateContractView(View):
    def get(self, request):
        # Получаем данные из параметров запроса
        customer_name = request.GET.get('customer_name', '')  # Получаем имя клиента из параметра запроса
        account_number = request.GET.get('account_number', '')  # Получаем номер счета из параметра запроса
        print(customer_name)
        # Создаем документ Word
        document = Document()
        document.add_heading('Договор о открытии счета', level=1)
        document.add_paragraph('Дата: ' + datetime.now().strftime('%d.%m.%Y'))
        document.add_paragraph()
        document.add_paragraph('Мы, банк "Название банка", именуемый в дальнейшем "Банк",')
        document.add_paragraph('с одной стороны, и гражданин ' + customer_name + ',')
        document.add_paragraph('действующий от своего имени, именуемый в дальнейшем "Клиент", с другой стороны,')
        document.add_paragraph('заключили настоящий договор о нижеследующем:')
        document.add_paragraph()
        document.add_paragraph('1. Банк открывает Клиенту счет под номером ' + account_number + '.')
        document.add_paragraph()
        document.add_paragraph('Настоящий договор вступает в силу с момента его подписания и действует в течение указанного периода.')
        document.add_paragraph()
        document.add_paragraph('Подпись Банка: _________________     Подпись Клиента: _________________')

        # Сохраняем документ в байтовый поток
        document_stream = io.BytesIO()
        document.save(document_stream)
        document_stream.seek(0)

        # Отправляем документ как файл в ответ на запрос
        response = FileResponse(document_stream, as_attachment=True, filename='открытие_счета_{}.docx'.format(customer_name))
        return response

class ClientAccountsReportView(View):
    def get(self, request):
        # Получаем все счета клиента
        customer_id= request.GET.get('customer_id', '')
        client_accounts = Account.objects.filter(customer=customer_id)

        # Создаем документ Word
        document = Document()
        document.add_heading('Список счетов клиента', level=1)
        for account in client_accounts:
            document.add_paragraph('Номер счета: {}'.format(account.pk))
            document.add_paragraph('Тип счета: {}'.format(account.get_account_type_display()))

            document.add_paragraph()

        # Сохраняем документ в байтовый поток
        document_stream = io.BytesIO()
        document.save(document_stream)
        document_stream.seek(0)

        # Отправляем документ как файл в ответ на запрос
        response = FileResponse(document_stream, as_attachment=True, filename='счета_клиента_{}.docx'.format(customer_id))
        return response
def luhn_checksum(card_number):
    # Преобразуем номер карты в список цифр
    digits = [int(x) for x in str(card_number)]
    # Удваиваем каждую вторую цифру, начиная с предпоследней
    for i in range(len(digits) - 2, -1, -2):
        digits[i] *= 2
        # Если результат удвоения больше 9, вычитаем 9

abs/templates/account_cards.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Детали счета</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <form method="POST" action="">
        {% csrf_token %}
    <div class="container">
        <h1 class="mt-4">Детали счета</h1>
        <a href="{% url 'customer_detail' account.customer.id %}" class="btn btn-primary mb-4"><i class="fas fa-arrow-left"></i> Назад</a> <!-- Кнопка "Назад к клиенту" -->
        <div class="card mb-4">
            <div class="card-header">
                <strong>Информация по счёту</strong>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-6">
                        <p><strong>Номер счёта:</strong> {{ account.pk }}
                        <input type="hidden"  name="account_pk" value ="{{account.pk}}" required>
                        <input type="hidden"  name="customer_pk" value ="{{account.customer.id}}" required></p>
                        <p><strong>Тип счета:</strong> {{ account.get_account_type_display }}</p>
                        <p><strong>Валюта:</strong> {{ account.currency }}</p>
                    </div>
                </div>
            </div>

                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Выпустить карту для этого счета</button>
                    {% comment %} <a href="" class="btn btn-primary"><i class="fas fa-edit"></i> Выпустить карту для этого счета</a> <!-- Кнопка редактирования клиента --> {% endcomment %}
                </div>

        </div>
    </form>
        <div class="card">
            <div class="card-header">
                Карты выпущенные к этому счёту
            </div>
            <div class="card-body">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Номер карты</th>
                            <th>Срок действие карты</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for card in cards %}
                            <tr>
                                <td>{{ card.card_number }}</td>
                                <td>{{ card.expiration_date }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <!-- Подключаем необходимые скрипты -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

abs/templates/add_account.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Открытие нового счёта</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
</head>
<body>
    <div class="container">
        <h1 class="mt-4">Открытие нового счёта</h1>
        <a href="{% url 'customer_detail' customer %}" class="btn btn-primary mb-4"><i class="fas fa-arrow-left"></i> Назад</a> <!-- Кнопка "Назад к списку клиентов" -->
        <form method="POST" action="">
            {% csrf_token %}

            <input type="hidden"  name="customer_pk" value ={{customer}} required>
            <div class="form-group">
                <label for="id_type_account">Тип счёта</label>
                <select class="form-control" id="id_type_account" name="type_account">

                    <option value="Д">Дебетовый</option>
                    <option value="К">Кредитный</option>
                    <option value="Н">Накопительный</option>
                </select>
            </div>
            <div class="form-group">
                <label for="id_currency">Валюта</label>
                <select class="form-control" id="id_currency" name="currency">
                    {% for currency in currencies%}
                    <option value={{currency.pk}}>{{currency.name}}</option>
                    {% endfor%}
                </select>
            </div>


            <button type="submit" class="btn btn-success">Открыть</button>
        </form>
    </div>

    <!-- Подключаем необходимые скрипты -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

abs/templates/add_customers.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Добавление нового клиента</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
</head>
<body>
    <div class="container">
        <h1 class="mt-4">Добавление нового клиента</h1>
        <a href="{% url 'customer_list' %}" class="btn btn-primary mb-4"><i class="fas fa-arrow-left"></i> Назад</a> <!-- Кнопка "Назад к списку клиентов" -->
        <form method="POST" action="">
            {% csrf_token %}

            <div class="form-group">
                <label for="last_name">Фамилия:</label>
                <input type="text" class="form-control" id="last_name" name="last_name" placeholder="Фамилия" required>
            </div>
            <div class="form-group">
                <label for="first_name">Имя:</label>
                <input type="text" class="form-control" id="first_name" name="first_name" placeholder="Имя" required>
            </div>
            <div class="form-group">
                <label for="middle_name">Отчество:</label>
                <input type="text" class="form-control" id="middle_name" name="middle_name" placeholder="Отчество" required>
            </div>
            <div class="form-group">
                <label for="id_date_of_birth">Дата Рождения:</label>
                <input type="date" class="form-control" id="id_date_of_birth" name="date_of_birth"  required>
            </div>
            <div class="form-group">
                <label for="id_gender">Пол</label>
                <select class="form-control" id="id_gender" name="gender">
                    <option value="М">Мужской</option>
                    <option value="Ж">Женский</option>
                </select>
            </div>
            <div class="form-group">
                <label for="photo">Фото:</label>
                <input type="file" class="form-control" id="photo" name="photo" placeholder="photo" required>
            </div>
            <div class="form-group">
                <label for="email">Email:</label>
                <input type="email" class="form-control" id="email" name="email" placeholder="Email" required>
            </div>
            <div class="form-group">
                <label for="phone">Телефон:</label>
                <input type="text" class="form-control" id="phone" name="phone" placeholder="Телефон" required>
            </div>
            <div class="form-group">
                <label for="id_address">Адрес проживание:</label>
                <input type="text" class="form-control" id="id_address" name="address" required>
            </div>
            <div class="form-group">
                <label for="id_passport_number">Паспортые данные:</label>
                <input type="text" class="form-control" id="id_passport_number" name="passport_number" required>
            </div>

            <div class="form-group">
                <label for="id_password_issue_data">Дата получения паспорта:</label>
                <input type="date" class="form-control" id="id_password_issue_data" name="password_issue_data" required>
            </div>

            <button type="submit" class="btn btn-success">Добавить</button>
        </form>
    </div>

    <!-- Подключаем необходимые скрипты -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

abs/templates/confirm_delete_customer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete Customer</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        /* Добавьте сюда ваши собственные стили */
        body {
            padding: 20px;
        }
        .container {
            max-width: 600px;
            margin: auto;
        }
        h1 {
            margin-bottom: 20px;
        }
        .btn-confirm {
            margin-right: 10px;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Удаление клиента</h1>
        <p>Вы действительно хотите удалить Этого клиента "{{ customers.last_name }} {{ customers.first_name }} {{ customers.middle_name }}"?</p>
        <form method="post">
            {% csrf_token %}
            <a href="{% url 'customer_list' %}" class="btn btn-secondary btn-confirm">Отмена</a>
            <button type="submit" class="btn btn-danger btn-confirm">Удалить без возврата</button>
        </form>
    </div>
</body>
</html>

abs/templates/edit_customer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Customer</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <div class="container">
        <h1 class="mt-4">редактирования данных клиента</h1>
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="last_name">Фамилия:</label>
                <input type="text" class="form-control" id="last_name" name="last_name" placeholder="Фамилия" value="{{ customers.last_name}}" required>
            </div>
            <div class="form-group">
                <label for="first_name">Имя:</label>
                <input type="text" class="form-control" id="first_name" name="first_name" placeholder="Имя"
                value="{{ customers.first_name}}" required>
            </div>
            <div class="form-group">
                <label for="middle_name">Отчество:</label>
                <input type="text" class="form-control" id="middle_name" name="middle_name" placeholder="Отчество" value="{{ customers.middle_name}}" required>
            </div>
            <div class="form-group">
                <label for="id_date_of_birth">Дата Рождения:</label>
                <input type="date" class="form-control" id="id_date_of_birth" name="date_of_birth" value="{{ customers.date_of_birth|date:'Y-m-d' }}" required>
            </div>
            <div class="form-group">
                <label for="id_gender">Пол</label>
                <select class="form-control" id="id_gender" name="gender">
                    <option value="Мужской" {% if customers.gender == 'М' %}selected{% endif %}>Мужской</option>
                    <option value="Женский" {% if customers.gender == 'Ж' %}selected{% endif %}>Женский</option>
                </select>
            </div>
            <div class="form-group">
                <label for="email">Email:</label>
                <input type="email" class="form-control" id="email" name="email" placeholder="Email" value="{{ customers.email}}" required>
            </div>
            <div class="form-group">
                <label for="phone">Телефон:</label>
                <input type="text" class="form-control" id="phone" name="phone" placeholder="Телефон" value="{{ customers.phone_numder}}" required>
            </div>
            <div class="form-group">
                <label for="id_address">Адрес проживание:</label>
                <input type="text" class="form-control" id="id_address" name="address" value="{{ customers.address}}" required>
            </div>
            <div class="form-group">
                <label for="id_passport_number">Паспортые данные:</label>
                <input type="text" class="form-control" id="id_passport_number" name="passport_number" value="{{ customers.password_number }}" required>
            </div>

            <div class="form-group">
                <label for="id_password_issue_data">Дата получения паспорта:</label>
                <input type="date" class="form-control" id="id_password_issue_data" name="password_issue_data" value="{{ customers.password_issue_data|date:'Y-m-d' }}"required>
            </div>
            <!-- Добавьте другие поля редактирования здесь -->
            <button type="submit" class="btn btn-primary">Сохранить</button>
            <a href="{% url 'customer_list' %}" class="btn btn-secondary">Отменить</a>
        </form>
    </div>

    <!-- Подключаем необходимые скрипты -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>